In [57]:
"""
变更list中的数据类型
"""
a = [1,5,9]
b = ['2','9','7']
a_str = list(map(str,a)) # 变为 str
b_int = list(map(int,b)) # 变为 int

print(a_str)
print(b_int)

['1', '5', '9']
[2, 9, 7]


In [59]:
"""
输入数据以空格分隔，转换为list，注意list中的数据类型需为int
e.g.: 45 60 -> [45,60]
"""
raw_input = input('')
raw_list = raw_input.split(' ') # 指定分隔符
raw_list = list(map(int,raw_list)) # 变更list中数据类型
print(raw_list)

45 60
[45, 60]


In [54]:
"""
Python 中进行list和tuple的转换
"""
a = [1,3,4,5,"abc"]
b = tuple(a) # list -> tuple
c = list(b) # tuple -> list
print(b,"\n",type(b))
print(c,"\n",type(c))

(1, 3, 4, 5, 'abc') 
 <class 'tuple'>
[1, 3, 4, 5, 'abc'] 
 <class 'list'>


In [23]:
"""
数列的定义如下： 数列的第一项为n，以后各项为前一项的平方根，求数列的前m项的和

输入数据有多组，每组占一行，由两个整数n（n<10000）和m(m<1000)组成，n和m的含义如前所述。

对于每组输入数据，输出该数列的和，每个测试实例占一行，要求精度保留2位小数。

样例输入
81 4
2 2

样例输出
94.73
3.41
"""
raw = input('')
nm = list(map(int, raw.split(' ')))
sum = 0
if nm[0] < 10000 and nm[1] < 1000:
    for i in range(nm[1]):
        x = nm[0]**((0.5)**i)
        sum += x
    print(round(sum,2))
else:
    print("null")

81 4
94.73


In [48]:
"""
水仙花数”是指一个三位数，它的各位数字的立方和等于其本身，比如：153=1^3+5^3+3^3。 现在要求输出所有在m和n范围内的水仙花数。
 
输入
输入数据有多组，每组占一行，包括两个整数m和n（100<=m<=n<=999）。

输出
对于每个测试实例，要求输出所有在给定范围内的水仙花数，就是说，输出的水仙花数必须大于等于m,并且小于等于n。
如果有多个，则要求从小到大排列在一行内输出，之间用一个空格隔开; 如果给定的范围内不存在水仙花数，则输出no; 每个测试实例的输出占一行。


样例输入
100 120
300 380

样例输出
no
370 371
"""
raw = input('')
mn = list(map(int,raw.split(' ')))
result = []
if mn[0] >= 100 and mn[0] <= mn[1] and mn[1] <= 999:
    for i in range(mn[0],mn[1]):
        a = int(str(i)[0]) # 只有str可以切片，因此需先把数转换为str，切片后再转换回int
        b = int(str(i)[1])
        c = int(str(i)[2])
        if i == a**3 + b**3 + c**3:
            result.append(i)
    if len(result) ==0:
        print("no")
    else:
        output = " ".join(list(map(str,result)))
        print(output)
else:
    print("input error")

300 380
370 371


In [70]:
"""
同时计算最大公因数和最小公倍数
"""
raw = input('')
ab = list(map(int,raw.split(' ')))
a = ab[0]
b = ab[1]
while a != 0:
    a,b = b % a, a
print(b)
print(int((ab[0]*ab[1])/b))

99 12
3
396


In [77]:
"""
你有3个需要完成的任务，完成这3个任务是需要付出代价的。
首先，你可以不花任何代价的完成一个任务；然后，在完成了第i个任务之后，你可以花费|Ai - Aj|的代价完成第j个任务。|x|代表x的绝对值。
计算出完成所有任务的最小代价。

输入描述
一行3个整数A1,A2,A3，每个数字之间用一个空格分隔。所有数字都是整数，并且在[1,100]范围内。
==========================================================
思路：
1. 接受输入，转换为list映射int数列并排序，获取三个值a,b,c=大,中,小
2. 计算代价：c1=大-中,c2=中-小，总代价=c1+c2
"""
raw = input('') # 1 6 3
raw_list = list(map(int,raw.split(' ')))
raw_list.sort(reverse=True) # [6, 3, 1]
a,b,c = raw_list[0],raw_list[1],raw_list[2] # a=6, b=3, c=1
cost1 = a - b
cost2 = b - c
total_cost = cost1 + cost2
print(total_cost)

1 6 3
5


In [88]:
"""
小易准备去拜访他的朋友，他的家在0点，但是他的朋友的家在x点(x > 0)，均在一条坐标轴上。
小易每一次可以向前走1，2，3，4或者5步。问小易最少走多少次可以到达他的朋友的家。

输入描述:
一行包含一个数字x(1 <= x <= 1000000)，代表朋友家的位置。

样例输入->输出
4->1
10->2
==========================================================
思路：
1. 接受输入，类型转换为int
2. 除以5取整记做前面的步数s
3. 除以5区余，若不为0，则步数+1；若为0，则步数为s
"""
raw = int(input('')) # 11
s = raw // 5 # 2
r = raw % 5 # 1
if r == 0:
    print(s)
else:
    print(s+1) # 3

11
3


In [105]:
"""
在一条街上有n幢房子，标号从1到n，两个在标号上相差为1的房子视为相邻，这些房子中有k幢房子已有住户。
现你准备搬入这条街，你能搬入一幢房子的条件是这幢房子没有人住，与此同时由于你非常热爱与邻居交流，故而你需要你所入住的房子两边上都有住户。
现要你求最小的可能符合要求的房子数，以及最大的可能符合要求的房子数。

Note: 就样例来说，#代表已有住户，-代表空位，这种情况（###---)，没有满足条件的房子，为最小，故输出0
最大的情况为(#-#-#-)，此种情况有二个位置满足条件，为最大，故输出2

输入描述:
输入的一行为测试用例数t(1 <= t <= 200000)

接下来t行，每行含两个整数n和k，(1 <= n <= 1,000,000,000，0 <= k <= n)
- n 为访问总数
- k 为已住人数

输出描述:
对于每个用例输出最小的可能数以及最大的可能数
==========================================================
思路：由于只要输出最小值和最大值，且最小值一定位0，因此只需要考虑最大值，无需考虑中间的排列组合。
1. 首先接受输入t
2. 在次数t范围内，接收输入 n 和 k （int）
3. 如果n<3或者k>=n或k<2(已有住户至少有2户才能有两边邻居)则没有满足条件的情况，打印0
4. 否则计算最大情况（n-k或n-1中取最小值）并打印
"""
t = int(input().strip())
for _ in range(t):
    n, k = map(int, input('').strip().split())
    if n<3 or k>=n or k<2:
        solution = 0
    else:
        solution = min(n-k,k-1)
    print(0, solution)

1
3 2
0 1


In [107]:
"""
节日到啦，牛牛和妞妞邀请了好多客人来家里做客。
他们摆出了一座高高的香槟塔，牛牛负责听妞妞指挥，往香槟塔里倒香槟。
香槟塔有个很优雅的视觉效果就是如果这一层的香槟满了，就会从边缘处往下一层流去。
妞妞会发出两种指令，指令一是往第x层塔内倒体积为v的香槟，指令二是询问第k层塔香槟的体积为多少。
告诉你香槟塔每层香槟塔的初始容量，你能帮牛牛快速回答妞妞的询问吗？

输入描述:
第一行为两个整数n，m。表示香槟塔的总层数和指令条数。
第二行为n个整数ai，表示每层香槟塔的初始容量。
第三行到第2+m行有两种输入，一种输入是“2 x v”表示往第x层倒入体积为v的香槟；另一种输入是“1 k”表示询问第k层当前有多少香槟。
1 <= n, m <= 1000。
1 <= n ,m <= 200000，1 <= ai ,v <= 1000000000。


输出描述:
对于每个询问，输出一个整数，表示第k层香槟的容量。
==========================================================
思路：
1. 接收输入n,m
2. 在指令数量范围m内接收输入ai表示每层的初始容量,a用list储存每层容量
"""
n,m = [int(i) for i in input().split()]
a = list(map(int,input('').split(' '))
print(n,m)
for _ in range(m):
    a

5 2
3
5 2


In [108]:
"""
小Q是篮球训练队的教练，篮球队新加入了N名队员，第i名队员的篮球水平值为ai。
小Q现在要把他们按照以下的要求分为A队和B队进行训练:
1、A队的队员水平值之和严格大于B队的队员水平值之和
2、对于A队中的任意一名队员，如果把他分配到B队，A队的水平值之和就会严格小于B队的水平值之和。
3、每个队员必须要加入一个队伍
小Q现在想知道有多少种方案可以按照以上要求完成分队。

输入描述:
输入包括两行, 输入的第一行为一个正整数n(2 <= N <= 50), 表示队员的数量。
第二行包括N个正整数 ai(1 <= ai <= 6 x 104), 表示每名队员的篮球水平值, 以空格分割。

输出描述:
输出一个正整数, 表示方案数。

输入例子1:
4
5 4 7 6

输出例子1:
2
==========================================================
思路：
1. 接受输入n为队员数量
"""

5

In [121]:
import numpy as np
a = np.repeat(np.arange(5).reshape([1,-1]),10,axis = 0)+10.0
b = np.random.randint(5, size= a.shape)
c = np.argmin(a*b, axis=1)
b = np.zeros(a.shape)
b[np.arange(b.shape[0]), c] = 1
print(b)

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [4]:
a = range(100)
print(a[2-3])

99
